### ISSUE TITLE
Error when specifying dns in kitchen.yml

### ISSUE THREAD

**Issue by rspowell** [test-kitchen/kitchen-dokken#175] opened 2019-03-16 14:36 UTC
I need to provide my dns server to the container, but I get the following when providing "dns:"
[json: cannot unmarshal string into Go struct field HostConfig.Dns of type []string

---
driver:
  name: dokken
  chef_version: latest
  privileged: true
  volumes: [ '/var/lib/docker' ]

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos-7
  driver:
    image: dokken/centos-7
    privileged: true
    pid_one_command: /usr/lib/systemd/systemd
    dns: 10.7.226.20
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

suites:
  - name: default
    run_list:
    - recipe[st-postfix::default]
    attributes:
      dokken_test:
        revision: <%= `git rev-parse HEAD` %>

**Comment by majormoses** [comment] 2020-08-03 01:07
I believe that means you need to use an array rather than a string.

Try updating it to the following which I think should work:
```
dns:
- 10.7.226.20

**Comment by marcparadise** [comment] 2021-02-24 18:43
There has been no reply to the suggested change for quite some time; given that it should solve the issue, I am closing this one out.  Please feel free to re-open if the issue is occurring after making the suggested change.

**Closed by marcparadise** 2021-02-24 18:43 UTC
